topics = ['Adult',
          'Arts', 
          'Business', 
          'Computers', 
          'Games', 
          'Health', 
          'Home',
          'Kids',
          'News',
          'Recreation',
          'Reference',
          'Science',
          'Shopping',
          'Society',
          'Sports'
]